Step 1: Import lib

In [1]:
import pandas as pd

**step 2: reading or importing data**

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\mudassar\appdata\local\programs\python\python314\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\mudassar\appdata\local\programs\python\python314\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
df=pd.read_excel('concrete_mix_design_eda.xlsx')
print(df)

    cement_kg_m3  rha_kg_m3  mp_kg_m3  fa_kg_m3  ca_kg_m3  water_kg_m3  \
0            382       40.0      69.0     727.0    1043.0        194.0
1            372       27.0      10.0     617.0     912.0        141.0
2            294        6.0      15.0     624.0    1013.0        188.0
3            386       72.0      58.0     833.0    1023.0        167.0
4            351        NaN      69.0     822.0    1005.0        171.0
..           ...        ...       ...       ...       ...          ...
95           442       55.0      59.0     646.0    1136.0        175.0
96           442       16.0      62.0     698.0     903.0        151.0
97           312       37.0      31.0     654.0     915.0        180.0
98           402       23.0      32.0     767.0     923.0        158.0
99           284       68.0      66.0     651.0     979.0        151.0

    superplasticizer_%Binder  compressive_strength_91d_MPa
0                       1.21                         53.25
1                       2.41                         66.77
2                       1.85                         33.31
3                       1.47                         65.07
4                       1.49                         52.06
..                       ...                           ...
95                      1.04                         51.38
96                      0.77                         44.24
97                      0.65                         65.77
98                      2.38                         35.15
99                      1.33                         43.20

[100 rows x 8 columns]

Step 3: To see different parts of data like head, tail, shape, info,  etc

In [6]:
df.head(10)

,cement_kg_m3,rha_kg_m3,mp_kg_m3,fa_kg_m3,ca_kg_m3,water_kg_m3,superplasticizer_%Binder,compressive_strength_91d_MPa
0,382,40.0,69.0,727.0,1043.0,194.0,1.21,53.25
1,372,27.0,10.0,617.0,912.0,141.0,2.41,66.77
2,294,6.0,15.0,624.0,1013.0,188.0,1.85,33.31
3,386,72.0,58.0,833.0,1023.0,167.0,1.47,65.07
4,351,NaN,69.0,822.0,1005.0,171.0,1.49,52.06
5,300,11.0,2.0,653.0,1057.0,166.0,0.67,36.59
6,382,33.0,19.0,657.0,1046.0,159.0,0.68,46.45
7,401,32.0,58.0,666.0,1044.0,163.0,1.70,61.10
8,354,47.0,35.0,703.0,NaN,151.0,1.61,49.21
9,367,22.0,18.0,773.0,962.0,189.0,0.93,69.41

In [7]:
df.tail()

,cement_kg_m3,rha_kg_m3,mp_kg_m3,fa_kg_m3,ca_kg_m3,water_kg_m3,superplasticizer_%Binder,compressive_strength_91d_MPa
95,442,55.0,59.0,646.0,1136.0,175.0,1.04,51.38
96,442,16.0,62.0,698.0,903.0,151.0,0.77,44.24
97,312,37.0,31.0,654.0,915.0,180.0,0.65,65.77
98,402,23.0,32.0,767.0,923.0,158.0,2.38,35.15
99,284,68.0,66.0,651.0,979.0,151.0,1.33,43.20

In [ ]:
df.shape

(100, 8)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cement_kg_m3                  100 non-null    int64
 1   rha_kg_m3                     96 non-null     float64
 2   mp_kg_m3                      99 non-null     float64
 3   fa_kg_m3                      98 non-null     float64
 4   ca_kg_m3                      94 non-null     float64
 5   water_kg_m3                   99 non-null     float64
 6   superplasticizer_%Binder      99 non-null     float64
 7   compressive_strength_91d_MPa  100 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 6.4 KB

In [11]:
df.info

<bound method DataFrame.info of     cement_kg_m3  rha_kg_m3  mp_kg_m3  fa_kg_m3  ca_kg_m3  water_kg_m3  \
0            382       40.0      69.0     727.0    1043.0        194.0
1            372       27.0      10.0     617.0     912.0        141.0
2            294        6.0      15.0     624.0    1013.0        188.0
3            386       72.0      58.0     833.0    1023.0        167.0
4            351        NaN      69.0     822.0    1005.0        171.0
..           ...        ...       ...       ...       ...          ...
95           442       55.0      59.0     646.0    1136.0        175.0
96           442       16.0      62.0     698.0     903.0        151.0
97           312       37.0      31.0     654.0     915.0        180.0
98           402       23.0      32.0     767.0     923.0        158.0
99           284       68.0      66.0     651.0     979.0        151.0

    superplasticizer_%Binder  compressive_strength_91d_MPa
0                       1.21                         53.25
1                       2.41                         66.77
2                       1.85                         33.31
3                       1.47                         65.07
4                       1.49                         52.06
..                       ...                           ...
95                      1.04                         51.38
96                      0.77                         44.24
97                      0.65                         65.77
98                      2.38                         35.15
99                      1.33                         43.20

[100 rows x 8 columns]>

Step4: First, let's rename the columns for clarity

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cement_kg_m3                  100 non-null    int64
 1   rha_kg_m3                     96 non-null     float64
 2   mp_kg_m3                      99 non-null     float64
 3   fa_kg_m3                      98 non-null     float64
 4   ca_kg_m3                      94 non-null     float64
 5   water_kg_m3                   99 non-null     float64
 6   superplasticizer_%Binder      99 non-null     float64
 7   compressive_strength_91d_MPa  100 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 6.4 KB

In [13]:
#renmae the each columns
df.rename(columns={'rha_kg_m3':'Rice_Husk_Ash_kg_per_m3'},inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cement_kg_m3                  100 non-null    int64
 1   Rice_Husk_Ash_kg_per_m3       96 non-null     float64
 2   mp_kg_m3                      99 non-null     float64
 3   fa_kg_m3                      98 non-null     float64
 4   ca_kg_m3                      94 non-null     float64
 5   water_kg_m3                   99 non-null     float64
 6   superplasticizer_%Binder      99 non-null     float64
 7   compressive_strength_91d_MPa  100 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 6.4 KB

Step 5: Check the missing values.

In [15]:
#Check the missing values.
print(df.isnull().sum())

cement_kg_m3                    0
Rice_Husk_Ash_kg_per_m3         4
mp_kg_m3                        1
fa_kg_m3                        2
ca_kg_m3                        6
water_kg_m3                     1
superplasticizer_%Binder        1
compressive_strength_91d_MPa    0
dtype: int64

In [16]:
#percentage of missing values
per_null=df.isnull().mean()*100
print(per_null)

cement_kg_m3                    0.0
Rice_Husk_Ash_kg_per_m3         4.0
mp_kg_m3                        1.0
fa_kg_m3                        2.0
ca_kg_m3                        6.0
water_kg_m3                     1.0
superplasticizer_%Binder        1.0
compressive_strength_91d_MPa    0.0
dtype: float64

Step 6: Fill the missing values

In [18]:
##fill missing values with mean of the column
df.fillna(df.mean(),inplace=True)

In [19]:
#percentage of missing values
per_null=df.isnull().mean()*100
print(per_null)

cement_kg_m3                    0.0
Rice_Husk_Ash_kg_per_m3         0.0
mp_kg_m3                        0.0
fa_kg_m3                        0.0
ca_kg_m3                        0.0
water_kg_m3                     0.0
superplasticizer_%Binder        0.0
compressive_strength_91d_MPa    0.0
dtype: float64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cement_kg_m3                  100 non-null    int64
 1   Rice_Husk_Ash_kg_per_m3       100 non-null    float64
 2   mp_kg_m3                      100 non-null    float64
 3   fa_kg_m3                      100 non-null    float64
 4   ca_kg_m3                      100 non-null    float64
 5   water_kg_m3                   100 non-null    float64
 6   superplasticizer_%Binder      100 non-null    float64
 7   compressive_strength_91d_MPa  100 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 6.4 KB

Step 7: convert datatype of any column if necessary

In [22]:
#Step 7: convert datatype of any column if necessary
df['Rice_Husk_Ash_kg_per_m3']=df['Rice_Husk_Ash_kg_per_m3'].astype('int64')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cement_kg_m3                  100 non-null    int64
 1   Rice_Husk_Ash_kg_per_m3       100 non-null    int64
 2   mp_kg_m3                      100 non-null    float64
 3   fa_kg_m3                      100 non-null    float64
 4   ca_kg_m3                      100 non-null    float64
 5   water_kg_m3                   100 non-null    float64
 6   superplasticizer_%Binder      100 non-null    float64
 7   compressive_strength_91d_MPa  100 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 6.4 KB

In [ ]:
df['Rice_Husk_Ash_kg_per_m3'] = df['Rice_Husk_Ash_kg_per_m3'].astype('int64')
df['Marble_powder_kg_per_m3'] = df['Marble_powder_kg_per_m3'].astype('int64')
df['Fine Aggregate_kg_per_m3'] = df['Fine Aggregate_kg_per_m3'].astype('int64')
df['Course Aggregate_kg_per_m3'] = df['Course Aggregate_kg_per_m3'].astype('int64')
df['water_kg_m3'] = df['water_kg_m3'].astype('int64')
df['superplasticizer_%Binder'] = df['superplasticizer_%Binder'].astype('int64')
df['compressive_strength_91d_MPa'] = df['compressive_strength_91d_MPa'].astype('int64')

In [ ]:
#step8: Data sorting
df.sort_index()
df.sort_index(ascending=True)
df.sort_index(ascending=False)
df.sort_values
df.sort_values(ascending=False, by="weight")

In [26]:
df.sort_index(ascending=False)

,cement_kg_m3,Rice_Husk_Ash_kg_per_m3,mp_kg_m3,fa_kg_m3,ca_kg_m3,water_kg_m3,superplasticizer_%Binder,compressive_strength_91d_MPa
99,284,68,66.0,651.0,979.0,151.0,1.33,43.20
98,402,23,32.0,767.0,923.0,158.0,2.38,35.15
97,312,37,31.0,654.0,915.0,180.0,0.65,65.77
96,442,16,62.0,698.0,903.0,151.0,0.77,44.24
95,442,55,59.0,646.0,1136.0,175.0,1.04,51.38
...,...,...,...,...,...,...,...,...
4,351,38,69.0,822.0,1005.0,171.0,1.49,52.06
3,386,72,58.0,833.0,1023.0,167.0,1.47,65.07
2,294,6,15.0,624.0,1013.0,188.0,1.85,33.31
1,372,27,10.0,617.0,912.0,141.0,2.41,66.77
0,382,40,69.0,727.0,1043.0,194.0,1.21,53.25

In [29]:
df.sort_values(ascending=False, by="cement_kg_m3")

,cement_kg_m3,Rice_Husk_Ash_kg_per_m3,mp_kg_m3,fa_kg_m3,ca_kg_m3,water_kg_m3,superplasticizer_%Binder,compressive_strength_91d_MPa
29,449,51,47.0,638.0,933.0,185.0,0.79,38.20
40,446,27,53.0,849.0,1088.0,149.0,1.46,63.25
56,443,61,20.0,697.0,928.0,160.0,1.46,55.47
96,442,16,62.0,698.0,903.0,151.0,0.77,44.24
95,442,55,59.0,646.0,1136.0,175.0,1.04,51.38
...,...,...,...,...,...,...,...,...
53,287,61,67.0,814.0,1128.0,195.0,1.86,54.69
99,284,68,66.0,651.0,979.0,151.0,1.33,43.20
64,283,36,47.0,785.0,1089.0,188.0,0.59,50.94
17,281,2,0.0,726.0,1016.0,151.0,1.97,35.35
60,281,71,6.0,790.0,946.0,176.0,2.10,51.90

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cement_kg_m3                  100 non-null    int64
 1   Rice_Husk_Ash_kg_per_m3       100 non-null    int64
 2   mp_kg_m3                      100 non-null    float64
 3   fa_kg_m3                      100 non-null    float64
 4   ca_kg_m3                      100 non-null    float64
 5   water_kg_m3                   100 non-null    float64
 6   superplasticizer_%Binder      100 non-null    float64
 7   compressive_strength_91d_MPa  100 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 6.4 KB

#DATA VULIZATION

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Set matplotlib parameters for journal-quality figures (Elsevier/Springer standards)
plt.rcParams.update({
    'font.family': 'serif',
    'font.serif': ['Times New Roman'],
    'font.size': 10,
    'axes.labelsize': 10,
    'axes.titlesize': 12,
    'xtick.labelsize': 8,
    'ytick.labelsize': 8,
    'legend.fontsize': 8,
    'figure.dpi': 300,
    'savefig.dpi': 300,
    'savefig.format': 'pdf',
    'axes.grid': False,
    'axes.facecolor': 'white',
    'figure.facecolor': 'white'
})

# Color-blind safe palette
palette = sns.color_palette("colorblind")

def create_sample_dataframe():
    """Create a sample DataFrame matching the provided description."""
    np.random.seed(42)  # For reproducibility
    n = 100
    df = pd.DataFrame({
        'cement_kg_m3': np.random.randint(200, 500, n),
        'Rice_Husk_Ash_kg_per_m3': np.random.randint(0, 100, n),
        'mp_kg_m3': np.random.uniform(0, 200, n),
        'fa_kg_m3': np.random.uniform(500, 800, n),
        'ca_kg_m3': np.random.uniform(600, 1200, n),
        'water_kg_m3': np.random.uniform(150, 250, n),
        'superplasticizer_%Binder': np.random.uniform(0, 5, n),
        'compressive_strength_91d_MPa': np.random.uniform(20, 60, n)
    })
    return df

def preprocess_data(df):
    """Perform data preprocessing: report missing values and handle them."""
    # Report percentage of missing values per column
    missing_percent = (df.isnull().sum() / len(df)) * 100
    print("Percentage of missing values per column:")
    print(missing_percent)
    
    # Since all columns have 0% missing (as per description), no imputation needed.
    # If missing, apply mean imputation for numerical data (scientifically justified for small missing rates).
    # df.fillna(df.mean(), inplace=True)  # Uncomment if needed
    
    return df

def save_figure(fig, filename, interactive=False):
    """Save figure with meaningful filename."""
    if interactive:
        fig.write_html(f"{filename}.html")
    else:
        fig.savefig(f"{filename}.pdf", bbox_inches='tight')
        fig.savefig(f"{filename}.png", bbox_inches='tight')

def univariate_hist_kde(df, column):
    """Generate histogram + KDE for a numerical variable."""
    fig, ax = plt.subplots(figsize=(6, 4))
    sns.histplot(df[column], kde=True, ax=ax, color=palette[0])
    ax.set_xlabel(f"{column.replace('_', ' ').title()} ({get_unit(column)})")
    ax.set_ylabel("Frequency")
    ax.set_title(f"Distribution of {column.replace('_', ' ').title()}")
    save_figure(fig, f"univariate_hist_kde_{column}")
    plt.close()

def univariate_box_violin(df, column):
    """Generate boxplot and violin plot for outlier detection."""
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    sns.boxplot(y=df[column], ax=axes[0], color=palette[1])
    axes[0].set_ylabel(f"{column.replace('_', ' ').title()} ({get_unit(column)})")
    axes[0].set_title("Boxplot")
    
    sns.violinplot(y=df[column], ax=axes[1], color=palette[2])
    axes[1].set_ylabel(f"{column.replace('_', ' ').title()} ({get_unit(column)})")
    axes[1].set_title("Violin Plot")
    
    save_figure(fig, f"univariate_box_violin_{column}")
    plt.close()

def bivariate_scatter_regression(df, x_col, y_col='compressive_strength_91d_MPa'):
    """Generate scatter plot with regression line."""
    fig, ax = plt.subplots(figsize=(6, 4))
    sns.regplot(x=df[x_col], y=df[y_col], ax=ax, scatter_kws={'alpha':0.6}, line_kws={'color':palette[3]})
    ax.set_xlabel(f"{x_col.replace('_', ' ').title()} ({get_unit(x_col)})")
    ax.set_ylabel(f"Compressive Strength (MPa)")
    ax.set_title(f"{x_col.replace('_', ' ').title()} vs Compressive Strength")
    save_figure(fig, f"bivariate_scatter_{x_col}_vs_strength")
    plt.close()

def multivariate_pairplot(df, vars_list):
    """Generate pairplot for key variables."""
    pairplot = sns.pairplot(df[vars_list], diag_kind='kde', plot_kws={'alpha':0.6})
    pairplot.fig.suptitle("Pairplot of Key Variables", y=1.02)
    save_figure(pairplot.fig, "multivariate_pairplot_key_vars")
    plt.close()

def correlation_heatmaps(df):
    """Generate Pearson and Spearman correlation heatmaps."""
    numerical_cols = df.select_dtypes(include=[np.number]).columns
    pearson_corr = df[numerical_cols].corr(method='pearson')
    spearman_corr = df[numerical_cols].corr(method='spearman')
    
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    sns.heatmap(pearson_corr, annot=True, cmap='viridis', ax=axes[0], fmt='.2f', cbar=False)
    axes[0].set_title("Pearson Correlation")
    
    sns.heatmap(spearman_corr, annot=True, cmap='viridis', ax=axes[1], fmt='.2f', cbar=False)
    axes[1].set_title("Spearman Correlation")
    
    save_figure(fig, "correlation_heatmaps")
    plt.close()

def categorical_cement_bins(df):
    """Cement-bin-wise comparison of compressive strength using boxplot and violin plot."""
    # Bin cement into categories
    df['cement_bins'] = pd.cut(df['cement_kg_m3'], bins=3, labels=['Low', 'Medium', 'High'])
    
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    sns.boxplot(x='cement_bins', y='compressive_strength_91d_MPa', data=df, ax=axes[0], palette=palette)
    axes[0].set_xlabel("Cement Bins (kg/m³)")
    axes[0].set_ylabel("Compressive Strength (MPa)")
    axes[0].set_title("Boxplot: Cement Bins vs Strength")
    
    sns.violinplot(x='cement_bins', y='compressive_strength_91d_MPa', data=df, ax=axes[1], palette=palette)
    axes[1].set_xlabel("Cement Bins (kg/m³)")
    axes[1].set_ylabel("Compressive Strength (MPa)")
    axes[1].set_title("Violin Plot: Cement Bins vs Strength")
    
    save_figure(fig, "categorical_cement_bins_vs_strength")
    plt.close()

def advanced_3d_scatter(df):
    """Generate 3D interactive scatter plot."""
    fig = px.scatter_3d(df, x='cement_kg_m3', y='water_kg_m3', z='compressive_strength_91d_MPa',
                        labels={'cement_kg_m3': 'Cement (kg/m³)', 'water_kg_m3': 'Water (kg/m³)', 'compressive_strength_91d_MPa': 'Strength (MPa)'},
                        title="3D Scatter: Cement, Water, and Strength")
    save_figure(fig, "advanced_3d_scatter", interactive=True)

def advanced_parallel_coordinates(df):
    """Generate parallel coordinates plot."""
    vars_list = ['cement_kg_m3', 'Rice_Husk_Ash_kg_per_m3', 'water_kg_m3', 'superplasticizer_%Binder', 'compressive_strength_91d_MPa']
    fig = px.parallel_coordinates(df[vars_list], color='compressive_strength_91d_MPa',
                                  labels={col: col.replace('_', ' ').title() + f" ({get_unit(col)})" for col in vars_list},
                                  title="Parallel Coordinates: Mix Constituents vs Strength")
    save_figure(fig, "advanced_parallel_coordinates", interactive=True)

def get_unit(column):
    """Helper to get units for columns."""
    units = {
        'cement_kg_m3': 'kg/m³',
        'Rice_Husk_Ash_kg_per_m3': 'kg/m³',
        'mp_kg_m3': 'kg/m³',
        'fa_kg_m3': 'kg/m³',
        'ca_kg_m3': 'kg/m³',
        'water_kg_m3': 'kg/m³',
        'superplasticizer_%Binder': '% Binder',
        'compressive_strength_91d_MPa': 'MPa'
    }
    return units.get(column, '')

def main():
    """Main function to run EDA and generate all figures."""
    df = create_sample_dataframe()
    df = preprocess_data(df)
    
    numerical_cols = df.select_dtypes(include=[np.number]).columns
    
    # A. Univariate analysis
    for col in numerical_cols:
        univariate_hist_kde(df, col)
        univariate_box_violin(df, col)
    
    # B. Bivariate & multivariate analysis
    input_cols = [col for col in numerical_cols if col != 'compressive_strength_91d_MPa']
    for col in input_cols:
        bivariate_scatter_regression(df, col)
    
    key_vars = ['cement_kg_m3', 'water_kg_m3', 'compressive_strength_91d_MPa']
    multivariate_pairplot(df, key_vars)
    correlation_heatmaps(df)
    
    # C. Categorical analysis
    categorical_cement_bins(df)
    
    # D. Advanced visualizations
    advanced_3d_scatter(df)
    advanced_parallel_coordinates(df)

if __name__ == "__main__":
    main()

Percentage of missing values per column:
cement_kg_m3                    0.0
Rice_Husk_Ash_kg_per_m3         0.0
mp_kg_m3                        0.0
fa_kg_m3                        0.0
ca_kg_m3                        0.0
water_kg_m3                     0.0
superplasticizer_%Binder        0.0
compressive_strength_91d_MPa    0.0
dtype: float64