Step1: Install and import library

In [1]:
import pandas as pd

Step2: Read and import data set

In [3]:
#pip install openpyxl
df=pd.read_excel('concrete_mix_design_eda.xlsx')

In [4]:
print(df)

    cement_kg_m3  rha_kg_m3  mp_kg_m3  fa_kg_m3  ca_kg_m3  water_kg_m3  \
0            382       40.0      69.0     727.0    1043.0        194.0
1            372       27.0      10.0     617.0     912.0        141.0
2            294        6.0      15.0     624.0    1013.0        188.0
3            386       72.0      58.0     833.0    1023.0        167.0
4            351        NaN      69.0     822.0    1005.0        171.0
..           ...        ...       ...       ...       ...          ...
95           442       55.0      59.0     646.0    1136.0        175.0
96           442       16.0      62.0     698.0     903.0        151.0
97           312       37.0      31.0     654.0     915.0        180.0
98           402       23.0      32.0     767.0     923.0        158.0
99           284       68.0      66.0     651.0     979.0        151.0

    superplasticizer_%Binder  compressive_strength_91d_MPa
0                       1.21                         53.25
1                       2.41                         66.77
2                       1.85                         33.31
3                       1.47                         65.07
4                       1.49                         52.06
..                       ...                           ...
95                      1.04                         51.38
96                      0.77                         44.24
97                      0.65                         65.77
98                      2.38                         35.15
99                      1.33                         43.20

[100 rows x 8 columns]

Step3: To see different parts of data like head, tail, shape, info,  etc

In [5]:
df.head()

,cement_kg_m3,rha_kg_m3,mp_kg_m3,fa_kg_m3,ca_kg_m3,water_kg_m3,superplasticizer_%Binder,compressive_strength_91d_MPa
0,382,40.0,69.0,727.0,1043.0,194.0,1.21,53.25
1,372,27.0,10.0,617.0,912.0,141.0,2.41,66.77
2,294,6.0,15.0,624.0,1013.0,188.0,1.85,33.31
3,386,72.0,58.0,833.0,1023.0,167.0,1.47,65.07
4,351,NaN,69.0,822.0,1005.0,171.0,1.49,52.06

In [6]:
df.head(10)

,cement_kg_m3,rha_kg_m3,mp_kg_m3,fa_kg_m3,ca_kg_m3,water_kg_m3,superplasticizer_%Binder,compressive_strength_91d_MPa
0,382,40.0,69.0,727.0,1043.0,194.0,1.21,53.25
1,372,27.0,10.0,617.0,912.0,141.0,2.41,66.77
2,294,6.0,15.0,624.0,1013.0,188.0,1.85,33.31
3,386,72.0,58.0,833.0,1023.0,167.0,1.47,65.07
4,351,NaN,69.0,822.0,1005.0,171.0,1.49,52.06
5,300,11.0,2.0,653.0,1057.0,166.0,0.67,36.59
6,382,33.0,19.0,657.0,1046.0,159.0,0.68,46.45
7,401,32.0,58.0,666.0,1044.0,163.0,1.70,61.10
8,354,47.0,35.0,703.0,NaN,151.0,1.61,49.21
9,367,22.0,18.0,773.0,962.0,189.0,0.93,69.41

In [7]:
df.tail()

,cement_kg_m3,rha_kg_m3,mp_kg_m3,fa_kg_m3,ca_kg_m3,water_kg_m3,superplasticizer_%Binder,compressive_strength_91d_MPa
95,442,55.0,59.0,646.0,1136.0,175.0,1.04,51.38
96,442,16.0,62.0,698.0,903.0,151.0,0.77,44.24
97,312,37.0,31.0,654.0,915.0,180.0,0.65,65.77
98,402,23.0,32.0,767.0,923.0,158.0,2.38,35.15
99,284,68.0,66.0,651.0,979.0,151.0,1.33,43.20

In [10]:
df.shape

(100, 8)

In [11]:
df.info

<bound method DataFrame.info of     cement_kg_m3  rha_kg_m3  mp_kg_m3  fa_kg_m3  ca_kg_m3  water_kg_m3  \
0            382       40.0      69.0     727.0    1043.0        194.0
1            372       27.0      10.0     617.0     912.0        141.0
2            294        6.0      15.0     624.0    1013.0        188.0
3            386       72.0      58.0     833.0    1023.0        167.0
4            351        NaN      69.0     822.0    1005.0        171.0
..           ...        ...       ...       ...       ...          ...
95           442       55.0      59.0     646.0    1136.0        175.0
96           442       16.0      62.0     698.0     903.0        151.0
97           312       37.0      31.0     654.0     915.0        180.0
98           402       23.0      32.0     767.0     923.0        158.0
99           284       68.0      66.0     651.0     979.0        151.0

    superplasticizer_%Binder  compressive_strength_91d_MPa
0                       1.21                         53.25
1                       2.41                         66.77
2                       1.85                         33.31
3                       1.47                         65.07
4                       1.49                         52.06
..                       ...                           ...
95                      1.04                         51.38
96                      0.77                         44.24
97                      0.65                         65.77
98                      2.38                         35.15
99                      1.33                         43.20

[100 rows x 8 columns]>

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cement_kg_m3                  100 non-null    int64
 1   rha_kg_m3                     96 non-null     float64
 2   mp_kg_m3                      99 non-null     float64
 3   fa_kg_m3                      98 non-null     float64
 4   ca_kg_m3                      94 non-null     float64
 5   water_kg_m3                   99 non-null     float64
 6   superplasticizer_%Binder      99 non-null     float64
 7   compressive_strength_91d_MPa  100 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 6.4 KB

Step4:Rename column of df

In [36]:
#remane a specific column
df.rename(columns={'rha_kg_m3': 'Rice Husk Ash_kg_per_m3',
                   'mp_kg_m3': 'Marble_powder_kg_per_m3',
                   'fa_kg_m3': 'Fine Aggregate_kg_per_m3',
                   'ca_kg_m3': 'Course Aggregate_kg_per_m3'},inplace=True)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cement_kg_m3                  100 non-null    int64
 1   Rice Husk Ash_kg_per_m3)      96 non-null     float64
 2   Marble_powder_kg_per_m3       99 non-null     float64
 3   Fine Aggregate_kg_per_m3      98 non-null     float64
 4   Course Aggregate_kg_per_m3    94 non-null     float64
 5   water_kg_m3                   99 non-null     float64
 6   superplasticizer_%Binder      99 non-null     float64
 7   compressive_strength_91d_MPa  100 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 6.4 KB

Step 5: Inspect the missing values.

In [44]:
#Check the missing values
print(df.isnull().sum())

cement_kg_m3                    0
Rice Husk Ash_kg_per_m3)        4
Marble_powder_kg_per_m3         1
Fine Aggregate_kg_per_m3        2
Course Aggregate_kg_per_m3      6
water_kg_m3                     1
superplasticizer_%Binder        1
compressive_strength_91d_MPa    0
dtype: int64

In [50]:
#percentage of null values
percent_null=df.isnull().mean()*100
print(percent_null)

cement_kg_m3                    0.0
Rice Husk Ash_kg_per_m3)        4.0
Marble_powder_kg_per_m3         1.0
Fine Aggregate_kg_per_m3        2.0
Course Aggregate_kg_per_m3      6.0
water_kg_m3                     1.0
superplasticizer_%Binder        1.0
compressive_strength_91d_MPa    0.0
dtype: float64

step6: fill missing values

In [51]:
#fill missing values with mean
df.fillna(df.mean(),inplace=True)

In [52]:
#percentage of null values
percent_null=df.isnull().mean()*100
print(percent_null)

cement_kg_m3                    0.0
Rice Husk Ash_kg_per_m3)        0.0
Marble_powder_kg_per_m3         0.0
Fine Aggregate_kg_per_m3        0.0
Course Aggregate_kg_per_m3      0.0
water_kg_m3                     0.0
superplasticizer_%Binder        0.0
compressive_strength_91d_MPa    0.0
dtype: float64

**step7: convert datatype of any column if necessary**

In [59]:
df['Rice Husk Ash_kg_per_m3)'] = df['Rice Husk Ash_kg_per_m3)'].astype('int64')
df['Marble_powder_kg_per_m3'] = df['Marble_powder_kg_per_m3'].astype('int64')
df['Fine Aggregate_kg_per_m3'] = df['Fine Aggregate_kg_per_m3'].astype('int64')
df['Course Aggregate_kg_per_m3'] = df['Course Aggregate_kg_per_m3'].astype('int64')
df['water_kg_m3'] = df['water_kg_m3'].astype('int64')
df['superplasticizer_%Binder'] = df['superplasticizer_%Binder'].astype('int64')
df['compressive_strength_91d_MPa'] = df['compressive_strength_91d_MPa'].astype('int64')

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cement_kg_m3                  100 non-null    int64
 1   Rice Husk Ash_kg_per_m3)      100 non-null    int64
 2   Marble_powder_kg_per_m3       100 non-null    int64
 3   Fine Aggregate_kg_per_m3      100 non-null    int64
 4   Course Aggregate_kg_per_m3    100 non-null    int64
 5   water_kg_m3                   100 non-null    int64
 6   superplasticizer_%Binder      100 non-null    int64
 7   compressive_strength_91d_MPa  100 non-null    int64
dtypes: int64(8)
memory usage: 6.4 KB

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from sklearn.impute import SimpleImputer
from scipy.stats import pearsonr, spearmanr
import warnings
warnings.filterwarnings('ignore')

# Set global plotting styles for journal quality
plt.rcParams.update({
    'font.family': 'serif',
    'font.serif': ['Times New Roman'],
    'font.size': 10,
    'axes.labelsize': 10,
    'axes.titlesize': 12,
    'xtick.labelsize': 8,
    'ytick.labelsize': 8,
    'legend.fontsize': 8,
    'figure.figsize': (8, 6),
    'savefig.dpi': 300,
    'savefig.format': 'pdf',
    'axes.grid': False,
    'axes.facecolor': 'white'
})
sns.set_palette("colorblind")  # Color-blind safe palette

# Create sample DataFrame based on description (for executability)
np.random.seed(42)
n = 100
df = pd.DataFrame({
    'cement_kg_m3': np.random.randint(200, 500, n),
    'rice_husk_ash_kg_m3': np.random.uniform(0, 50, n),
    'marbal_powder_kg_m3': np.random.uniform(0, 100, n),
    'fa_kg_m3': np.random.uniform(500, 800, n),
    'ca_kg_m3': np.random.uniform(1000, 1500, n),
    'water_kg_m3': np.random.uniform(150, 250, n),
    'superplasticizer_%Binder': np.random.uniform(0, 2, n),
    'compressive_strength_91d_MPa': np.random.uniform(20, 60, n),
    'cement_bins': pd.Categorical(np.random.choice(['Low', 'Medium', 'High'], n))
})

# Introduce missing values as per description
df.loc[np.random.choice(n, 4, replace=False), 'rice_husk_ash_kg_m3'] = np.nan
df.loc[np.random.choice(n, 1, replace=False), 'marbal_powder_kg_m3'] = np.nan
df.loc[np.random.choice(n, 2, replace=False), 'fa_kg_m3'] = np.nan
df.loc[np.random.choice(n, 6, replace=False), 'ca_kg_m3'] = np.nan
df.loc[np.random.choice(n, 1, replace=False), 'water_kg_m3'] = np.nan
df.loc[np.random.choice(n, 1, replace=False), 'superplasticizer_%Binder'] = np.nan

# Data preprocessing
def preprocess_data(df):
    # Report percentage of missing values per column
    missing_pct = df.isnull().sum() / len(df) * 100
    print("Percentage of missing values per column:")
    print(missing_pct)
    
    # Scientifically justified handling: Use mean imputation for continuous variables (assuming MAR and normal distribution)
    # For categorical, no imputation needed as it's complete
    num_cols = df.select_dtypes(include=[np.number]).columns
    imputer = SimpleImputer(strategy='mean')
    df[num_cols] = imputer.fit_transform(df[num_cols])
    
    return df

df = preprocess_data(df)

# Numerical columns for analysis
num_cols = ['cement_kg_m3', 'rice_husk_ash_kg_m3', 'marbal_powder_kg_m3', 'fa_kg_m3', 'ca_kg_m3', 'water_kg_m3', 'superplasticizer_%Binder', 'compressive_strength_91d_MPa']
key_vars = ['cement_kg_m3', 'water_kg_m3', 'compressive_strength_91d_MPa']  # Key variables for pairplot to avoid clutter

# Function to save figures
def save_figure(fig, filename, interactive=False):
    if interactive:
        fig.write_html(f"{filename}.html")
    else:
        fig.savefig(f"{filename}.pdf", bbox_inches='tight')
        fig.savefig(f"{filename}.png", bbox_inches='tight')

# A. Univariate analysis
def plot_univariate(df, col):
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    # Histogram + KDE
    sns.histplot(df[col], kde=True, ax=axes[0])
    axes[0].set_title(f'Histogram + KDE of {col.replace("_", " ").title()}')
    axes[0].set_xlabel(f'{col.replace("_", " ").title()} ({get_unit(col)})')
    axes[0].set_ylabel('Frequency')
    
    # Boxplot
    sns.boxplot(y=df[col], ax=axes[1])
    axes[1].set_title(f'Boxplot of {col.replace("_", " ").title()}')
    axes[1].set_ylabel(f'{col.replace("_", " ").title()} ({get_unit(col)})')
    
    # Violin plot
    sns.violinplot(y=df[col], ax=axes[2])
    axes[2].set_title(f'Violin Plot of {col.replace("_", " ").title()}')
    axes[2].set_ylabel(f'{col.replace("_", " ").title()} ({get_unit(col)})')
    
    plt.tight_layout()
    save_figure(fig, f'univariate_{col}')
    plt.close()

def get_unit(col):
    units = {
        'cement_kg_m3': 'kg/m³',
        'rice_husk_ash_kg_m3': 'kg/m³',
        'marbal_powder_kg_m3': 'kg/m³',
        'fa_kg_m3': 'kg/m³',
        'ca_kg_m3': 'kg/m³',
        'water_kg_m3': 'kg/m³',
        'superplasticizer_%Binder': '% Binder',
        'compressive_strength_91d_MPa': 'MPa'
    }
    return units.get(col, '')

for col in num_cols:
    plot_univariate(df, col)

# B. Bivariate & multivariate analysis
def plot_scatter_regression(df, x_col, y_col='compressive_strength_91d_MPa'):
    fig, ax = plt.subplots(figsize=(8, 6))
    sns.regplot(x=x_col, y=y_col, data=df, ax=ax, scatter_kws={'alpha':0.6})
    ax.set_title(f'Scatter Plot: {x_col.replace("_", " ").title()} vs {y_col.replace("_", " ").title()}')
    ax.set_xlabel(f'{x_col.replace("_", " ").title()} ({get_unit(x_col)})')
    ax.set_ylabel(f'{y_col.replace("_", " ").title()} ({get_unit(y_col)})')
    plt.tight_layout()
    save_figure(fig, f'scatter_{x_col}_vs_{y_col}')
    plt.close()

for col in num_cols[:-1]:  # Exclude strength itself
    plot_scatter_regression(df, col)

# Pairplot for key variables
def plot_pairplot(df, vars_list):
    g = sns.pairplot(df[vars_list], diag_kind='kde', plot_kws={'alpha':0.6})
    g.fig.suptitle('Pairplot of Key Variables', y=1.02)
    for ax in g.axes.flatten():
        if ax:
            xlabel = ax.get_xlabel()
            ylabel = ax.get_ylabel()
            if xlabel in vars_list:
                ax.set_xlabel(f'{xlabel.replace("_", " ").title()} ({get_unit(xlabel)})')
            if ylabel in vars_list:
                ax.set_ylabel(f'{ylabel.replace("_", " ").title()} ({get_unit(ylabel)})')
    save_figure(g.fig, 'pairplot_key_vars')
    plt.close()

plot_pairplot(df, key_vars)

# Correlation heatmaps
def plot_correlation_heatmap(df, method='pearson'):
    corr = df[num_cols].corr(method=method)
    fig, ax = plt.subplots(figsize=(10, 8))
    mask = np.triu(np.ones_like(corr, dtype=bool))
    sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='viridis', ax=ax, cbar_kws={'shrink': 0.8})
    ax.set_title(f'{method.capitalize()} Correlation Heatmap')
    save_figure(fig, f'correlation_heatmap_{method}')
    plt.close()

plot_correlation_heatmap(df, 'pearson')
plot_correlation_heatmap(df, 'spearman')

# C. Categorical analysis
def plot_categorical_comparison(df, cat_col='cement_bins', num_col='compressive_strength_91d_MPa'):
    fig, axes = plt.subplots(1, 2, figsize=(12, 6))
    
    # Boxplot
    sns.boxplot(x=cat_col, y=num_col, data=df, ax=axes[0])
    axes[0].set_title(f'Boxplot: {num_col.replace("_", " ").title()} by {cat_col.replace("_", " ").title()}')
    axes[0].set_xlabel(cat_col.replace("_", " ").title())
    axes[0].set_ylabel(f'{num_col.replace("_", " ").title()} ({get_unit(num_col)})')
    
    # Violin plot
    sns.violinplot(x=cat_col, y=num_col, data=df, ax=axes[1])
    axes[1].set_title(f'Violin Plot: {num_col.replace("_", " ").title()} by {cat_col.replace("_", " ").title()}')
    axes[1].set_xlabel(cat_col.replace("_", " ").title())
    axes[1].set_ylabel(f'{num_col.replace("_", " ").title()} ({get_unit(num_col)})')
    
    plt.tight_layout()
    save_figure(fig, f'categorical_{cat_col}_vs_{num_col}')
    plt.close()

plot_categorical_comparison(df)

# D. Advanced visualizations (Interactive with Plotly)
# 3D Scatter Plot
def plot_3d_scatter(df):
    fig = px.scatter_3d(df, x='cement_kg_m3', y='water_kg_m3', z='compressive_strength_91d_MPa',
                        title='3D Scatter Plot: Cement, Water, and Compressive Strength',
                        labels={'cement_kg_m3': 'Cement (kg/m³)', 'water_kg_m3': 'Water (kg/m³)', 'compressive_strength_91d_MPa': 'Strength (MPa)'})
    fig.update_layout(scene=dict(xaxis_title='Cement (kg/m³)', yaxis_title='Water (kg/m³)', zaxis_title='Strength (MPa)'))
    save_figure(fig, '3d_scatter_cement_water_strength', interactive=True)

plot_3d_scatter(df)

# Parallel Coordinates Plot
def plot_parallel_coordinates(df):
    vars_for_parallel = ['cement_kg_m3', 'rice_husk_ash_kg_m3', 'marbal_powder_kg_m3', 'fa_kg_m3', 'ca_kg_m3', 'water_kg_m3', 'superplasticizer_%Binder', 'compressive_strength_91d_MPa']
    fig = px.parallel_coordinates(df[vars_for_parallel], color='compressive_strength_91d_MPa',
                                  labels={col: f'{col.replace("_", " ").title()} ({get_unit(col)})' for col in vars_for_parallel},
                                  title='Parallel Coordinates Plot of Mix Constituents vs Strength')
    save_figure(fig, 'parallel_coordinates_mix_vs_strength', interactive=True)

plot_parallel_coordinates(df)